/tracking/verbose 1
/event/verbose 1

# change world parameter
/usr/det/setField 0.0 tesla
#/usr/det/setMaxStep  1.0 cm

#inactivate msc
#/process/inactivate msc

/gun/position 0 0 0 cm
/gun/direction 0 0 1
/gun/particle neutron
/gun/energy 0.500 MeV

#/process/em/fluo true
#/process/em/auger true
#/process/em/augerCascade true

#/usr/det/setMaterial NaI
#/run/setCut 0.01 mm

/run/initialize

/run/beamOn 100

