/tracking/verbose 0
/event/verbose 0

# change world parameter
#/usr/det/setField 0.0 tesla
#/usr/det/setMaxStep  100 cm

/gun/usr/mode nAIST565
/gun/usr/particle neutron
#inactivate msc
#/process/inactivate msc

#/gun/position -100 0 0 cm
#/gun/direction 1 0 0
#/gun/particle neutron
#/gun/energy 0.565 MeV

#/process/em/fluo true
#/process/em/auger true
#/process/em/augerCascade true

#/usr/det/setMaterial NaI
#/run/setCut 0.01 mm
/usr/nShield/type cube
/usr/nShield/size 25 cm
/usr/gShield1/thickness 0 cm
/usr/gShield2/thickness 5 cm

/run/initialize

/run/beamOn 1000000

